image:
  file: Dockerfile  # Use the Dockerfile you created for the workspace

tasks:
  - name: Build Maven Project
    init: |
      mvn clean install  # Build the project
    command: |
      echo "Project setup is complete."
