image:
  file: Dockerfile

tasks:
  - name: Install Dependencies
    init: |
      echo "Updating packages and installing dependencies..."
      sudo apt-get update
      sudo apt-get install -y git wget unzip xvfb
      sudo apt-get install -y openjdk-17-jdk
    command: |
      echo "Dependencies installed successfully."

  - name: Build Maven Project
    init: echo "Building Maven project..."
    command: mvn clean install
