image:
  file: Dockerfile

tasks:
  - init: |
      sudo apt-get update
      sudo apt-get install -y wget unzip xvfb
      wget -q https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
      sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get -f install -y
      wget https://chromedriver.storage.googleapis.com/$(wget -q -O - https://chromedriver.storage.googleapis.com/LATEST_RELEASE)/chromedriver_linux64.zip
      unzip chromedriver_linux64.zip
      sudo mv chromedriver /usr/local/bin/
      sudo chmod +x /usr/local/bin/chromedriver
      sudo apt-get install -y openjdk-17-jdk maven
  command: |
      echo "Environment ready for Selenium with Java."
