image:
  file: Dockerfile

tasks:
  - name: Initialize Maven Project
    init: |
      echo "Building project dependencies..."
      mvn clean install
    command: |
      echo "Environment ready. You can run your Selenium tests."
